language: csharp

solution: GPUVerify.sln

env:
  global:
    - LLVM_VERSION=5.0
    - LLVM_FULL_VERSION="${LLVM_VERSION}.0"
    - Z3_VERSION=4.5.0
    - CVC4_VERSION=1.5
    - CLONE_DEPTH=50
    - BUILD_ROOT="${TRAVIS_BUILD_DIR}"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/downloads

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - g++
      - ninja-build
      - python-psutil
      # From sources above
      - llvm-5.0-dev
      - clang-5.0
      - clang-5.0-dev

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env:
        - CXX=g++
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
      script:
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      env:
        - CXX=g++
        - DEFAULT_SOLVER=cvc4
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
      script:
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      if: branch = master AND type = push
      env:
        - CXX="clang++-${LLVM_VERSION}"
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
        - LLVM="clang+llvm-${LLVM_FULL_VERSION}-linux-x86_64-ubuntu14.04"
      script:
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      if: branch = master AND type = push
      env:
        - CXX="clang++-${LLVM_VERSION}"
        - DEFAULT_SOLVER=cvc4
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
        - LLVM="clang+llvm-${LLVM_FULL_VERSION}-linux-x86_64-ubuntu14.04"
      script:
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
